import warnings
warnings.filterwarnings("ignore", category=DeprecationWarning)

import flet as ft
from modules.interface_components import CustomText
import webbrowser 

def info_page():
    return ft.Column(
        [
            ft.Image(
                src=f"https://avatars.githubusercontent.com/u/91035485?s=400&u=67a9a286015cdfbdf8fab3865c30e468113b208c&v=4",
                width=150,
                height=150,
                fit=ft.ImageFit.CONTAIN,
                repeat=ft.ImageRepeat.NO_REPEAT,
                border_radius=ft.border_radius.all(100),
            ),
            CustomText(value="Autor: Sidney Teodoro"),

            CustomText(value="Contact:"),

            CustomText(value="+55 (27) 99648-9123", color=ft.Colors.GREY_500, size=16),
            CustomText(value="sidneyteodoro2002@gmail.com", color=ft.Colors.GREY_500, size=16),
            CustomText(value="@sidney_teodoro_araujo", color=ft.Colors.GREY_500, size=16),

            CustomText(value="Importante", color=ft.Colors.RED_500),

            CustomText(value="""This APP was developed with the aim of providing an intuitive and functional platform. However, the developer is not responsible for the data generated by users, including, but not limited to, personal information, preferences and usage history. In addition, we have no control over links or resources accessed outside the application platform, and any interaction with external websites or third-party content is the sole responsibility of the user."""
                       ,color=ft.Colors.GREY_500, size=15),

            CustomText(value="Version: 0.1.0 (2024)", color=ft.Colors.GREY_500, size=15)
        ],
        alignment=ft.MainAxisAlignment.CENTER,
        horizontal_alignment=ft.CrossAxisAlignment.CENTER,
        spacing=20
    )
